version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
  build:
    commands:
      - echo building the application
      - mvn install
artifacts:
  files:
    - target/*.jar
    - scripts
    - appspec.yml
  discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'